jobs:

- name: queryBalance
  query-account:
      account: 326441B7D0FC68759343CE4ED2F0A86D31F9BFBB
      field: balance

- name: queryNodeBalance
  query-account:
      account: 0A37949103BDA9F2249BB3BFAF4D7F3D8421AEEE
      field: balance

