jobs:

- name: queryBalance
  query-account:
      account: DB06E1445BF33A2D7594CA8A12E810DC4E5634D7
      field: balance

- name: queryNodeBalance
  query-account:
      account: 6FF146E4595006E06E3B840CDA11CACEFA999020
      field: balance

