jobs:

- name: deploySmart
  set:
      val: 61ED0117AF183005AE68792C5304EDD73163D1E7 

- name: setStockid1
  set:
      val: 1 

- name: setStockname1
  set:
      val: pizza

- name: setStockamount1
  set:
      val: 10

- name: setStockprice1
  set:
      val: 2 

- name: setStockid2
  set:
      val: 2

- name: setStockname2
  set:
      val: Ete

- name: setStockamount2
  set:
      val: 10

- name: setStockprice2
  set:
      val: 1 

- name: setStockid3
  set:
      val: 3

- name: setStockname3
  set:
      val: StartBuck

- name: setStockamount3
  set:
      val: 10

- name: setStockprice3
  set:
      val: 2

- name: setStockid4
  set:
      val: 4

- name: setStockname4
  set:
      val: Swensens

- name: setStockamount4
  set:
      val: 10

- name: setStockprice4
  set:
      val: 1

- name: initailStock1
  call:
      destination: $deploySmart
      function: add_stock
      data: [$setStockid1,$setStockname1,$setStockamount1,$setStockprice1]

- name: initailStock2
  call:
      destination: $deploySmart
      function: add_stock
      data: [$setStockid2,$setStockname2,$setStockamount2,$setStockprice2]

- name: initailStock3
  call:
      destination: $deploySmart
      function: add_stock
      data: [$setStockid3,$setStockname3,$setStockamount3,$setStockprice3]

- name: initailStock4
  call:
      destination: $deploySmart
      function: add_stock
      data: [$setStockid4,$setStockname4,$setStockamount4,$setStockprice4]

- name: queryStockList
  call:
      destination: $deploySmart
      function: getStockList
      data:

