jobs:

- name: setAddr1
  set:
      val: 11

- name: setID1
  set:
      val: 1111 

- name: setName1
  set:
      val: PIN

- name: setAddr2
  set:
      val: 22

- name: setID2
  set:
      val: 2222 

- name: setName2
  set:
      val: SUN

- name: setAddr3
  set:
      val: 33 

- name: setID3
  set:
      val: 3333

- name: setName3
  set:
      val: BEER

- name: setAddr4
  set:
      val: 44

- name: setID4
  set:
      val: 4444

- name: setName4
  set:
      val: MEK

- name: setAddr5
  set:
      val: 55

- name: setID5
  set:
      val: 5555

- name: setName5
  set:
      val: To

- name: deploySmart
  deploy:
      contract: smart.sol

- name: initailEmp1
  call:
      destination: $deploySmart
      function: create_employee
      data: [$setAddr1,$setID1,$setName1]

- name: initailEmp2
  call:
      destination: $deploySmart
      function: create_employee
      data: [$setAddr2,$setID2,$setName2]

- name: initailEmp3
  call:
      destination: $deploySmart
      function: create_employee
      data: [$setAddr3,$setID3,$setName3]

- name: initailEmp4
  call:
      destination: $deploySmart
      function: create_employee
      data: [$setAddr4,$setID4,$setName4]

- name: initailEmp5
  call:
      destination: $deploySmart
      function: create_employee
      data: [$setAddr5,$setID5,$setName5]

- name: queryEmp1
  query-contract:
      destination: $deploySmart
      function: getEmployee
      data: [$setAddr1]

- name: queryEmp2
  query-contract:
      destination: $deploySmart
      function: getEmployee
      data: [$setAddr2]

- name: queryEmp3
  query-contract:
      destination: $deploySmart
      function: getEmployee
      data: [$setAddr3]

- name: queryEmp4
  query-contract:
      destination: $deploySmart
      function: getEmployee
      data: [$setAddr4]

- name: queryEmp5
  query-contract:
      destination: $deploySmart
      function: getEmployee
      data: [$setAddr5]

