jobs:
- name: account
  set:
      val: C09E56B1BE34AB5E8CF22011F8F2A6BB2141C5EA

- name: sendToken 
  send:
      destination: $account 
      amount: 100

- name: queryBalance
  query-account:
      account: $account
      field: balance

- name: permCall
  permission:
      action: setBase
      target: $account
      permission: call
      value: "true"

- name: permSend
  permission:
      action: setBase
      target: $account
      permission: send
      value: "true"

- name: permSend
  permission:
      action: setBase
      target: $account
      permission: root
      value: "true"



- name: queryPerm
  query-account:
      account: $account
      field: permissions.base


